import 'package:hive/hive.dart';

part 'flashcard.g.dart'; // This file will be generated by Hive

@HiveType(typeId: 0)
class Flashcard {
  @HiveField(0)
  final String id;
  @HiveField(1)
  final String question;
  @HiveField(2)
  final String answer;
  
  // Adding the key property to store Hive's internal key
  @HiveField(3)
  int? key;

  Flashcard({
    required this.id,
    required this.question,
    required this.answer,
    this.key, // Allow key to be optional during construction
  });
}
